### ISSUE TITLE
Direct Conversion mirrors spectrum in all apps

### ISSUE THREAD

**Issue by thereisnocat** [rigexpert/libfobos#4]
I’ve been able to connect to my new FobosSDR with HDSDR, SDRSharp, and uSDR on Windows, and in all apps I see the spectrum mirrored back on itself. For example, if I have the bandwidth set to 8 MHz, running from 0 to 8 MHz, if I have a station at 1000 kHz, I also have that station at 7000 kHz. If I have a station at 6000 kHz, I also have that station at 2000 kHz. This problem is not evident in the RF portion of the receiver above 25 MHz, but it makes the direct conversion part of the receiver from 0 to 25 MHz problematic. I get this no matter which setting I choose, IQ (both HF channels), HF1, or HF2.

**Comment by thereisnocat** [comment]
I also see this on SDR++ on the Mac.

**Comment by rigexpert** [comment]
This is not a libfobos issue. Mirrored spectrum is because of the sampling theorem and Fourier transform. 
HDSDR, SDRSharp and SDR++ can not deal with direct sampling spectrum correctly, but uSDR can do it. Third party software discussions are off top.

**Comment by thereisnocat** [comment]
Note that the Perseus22 and the RSPDuo both have dual receiver streams, and are the closest analogs to the Fobos in that sense, and neither of them exhibits this behavior.

**Comment by godsic** [comment]
@thereisnocat Fobos does direct sampling for HF inputs and puts HF1 and HF2 inputs into I and Q samples, respectively. If you then treat that data as normal IQ stream, then you might end up with all sorts of artifacts. So for HF inputs you should process I and Q as two completely independent real-valued streams. In addition, for HF inputs I would not set sampling rate to anything but 50MSps (or even 80 MSps if it is available in your libfobos build), because there are no antialiasing filters for smaller sampling rates and risks of getting severe aliasing are high.
